### ISSUE TITLE
pip install pyforms-terminal

### ISSUE THREAD

**Issue by wild-bil** [UmSenhorQualquer/pyforms-terminal#3]
Returns: Can anyone help?

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement pyforms-terminal (from versions: none)
ERROR: No matching distribution found for pyforms-terminal

**Comment by UmSenhorQualquer** [comment]
The versions for python2.7 of pyforms-terminal are no longer available. I suggest you do download the project directly from the repository and install it from there.
